package com.connectify.utils;

import java.util.HashMap;
import java.util.Map;

public class CountryList {
    private final Map<String,String> countriesMap = new HashMap<>();
    private void setCountries(){
        countriesMap.put("Abkhazia", "+7 840");
        countriesMap.put("Afghanistan", "+93");
        countriesMap.put("Albania", "+355");
        countriesMap.put("Algeria", "+213");
        countriesMap.put("American Samoa", "+1 684");
        countriesMap.put("Andorra", "+376");
        countriesMap.put("Angola", "+244");
        countriesMap.put("Anguilla", "+1 264");
        countriesMap.put("Antigua and Barbuda", "+1 268");
        countriesMap.put("Argentina", "+54");
        countriesMap.put("Armenia", "+374");
        countriesMap.put("Aruba", "+297");
        countriesMap.put("Ascension", "+247");
        countriesMap.put("Australia", "+61");
        countriesMap.put("Australian External Territories", "+672");
        countriesMap.put("Austria", "+43");
        countriesMap.put("Azerbaijan", "+994");
        countriesMap.put("Bahamas", "+1 242");
        countriesMap.put("Bahrain", "+973");
        countriesMap.put("Bangladesh", "+880");
        countriesMap.put("Barbados", "+1 246");
        countriesMap.put("Barbuda", "+1 268");
        countriesMap.put("Belarus", "+375");
        countriesMap.put("Belgium", "+32");
        countriesMap.put("Belize", "+501");
        countriesMap.put("Benin", "+229");
        countriesMap.put("Bermuda", "+1 441");
        countriesMap.put("Bhutan", "+975");
        countriesMap.put("Bolivia", "+591");
        countriesMap.put("Bosnia and Herzegovina", "+387");
        countriesMap.put("Botswana", "+267");
        countriesMap.put("Brazil", "+55");
        countriesMap.put("British Indian Ocean Territory", "+246");
        countriesMap.put("British Virgin Islands", "+1 284");
        countriesMap.put("Brunei", "+673");
        countriesMap.put("Bulgaria", "+359");
        countriesMap.put("Burkina Faso", "+226");
        countriesMap.put("Burundi", "+257");
        countriesMap.put("Cambodia", "+855");
        countriesMap.put("Cameroon", "+237");
        countriesMap.put("Canada", "+1");
        countriesMap.put("Cape Verde", "+238");
        countriesMap.put("Cayman Islands", "+ 345");
        countriesMap.put("Central African Republic", "+236");
        countriesMap.put("Chad", "+235");
        countriesMap.put("Chile", "+56");
        countriesMap.put("China", "+86");
        countriesMap.put("Christmas Island", "+61");
        countriesMap.put("Cocos-Keeling Islands", "+61");
        countriesMap.put("Colombia", "+57");
        countriesMap.put("Comoros", "+269");
        countriesMap.put("Congo", "+242");
        countriesMap.put("Congo, Dem. Rep. of (Zaire)", "+243");
        countriesMap.put("Cook Islands", "+682");
        countriesMap.put("Costa Rica", "+506");
        countriesMap.put("Croatia", "+385");
        countriesMap.put("Cuba", "+53");
        countriesMap.put("Curacao", "+599");
        countriesMap.put("Cyprus", "+537");
        countriesMap.put("Czech Republic", "+420");
        countriesMap.put("Denmark", "+45");
        countriesMap.put("Diego Garcia", "+246");
        countriesMap.put("Djibouti", "+253");
        countriesMap.put("Dominica", "+1 767");
        countriesMap.put("Dominican Republic", "+1 809");
        countriesMap.put("East Timor", "+670");
        countriesMap.put("Easter Island", "+56");
        countriesMap.put("Ecuador", "+593");
        countriesMap.put("Egypt", "+20");
        countriesMap.put("El Salvador", "+503");
        countriesMap.put("Equatorial Guinea", "+240");
        countriesMap.put("Eritrea", "+291");
        countriesMap.put("Estonia", "+372");
        countriesMap.put("Ethiopia", "+251");
        countriesMap.put("Falkland Islands", "+500");
        countriesMap.put("Faroe Islands", "+298");
        countriesMap.put("Fiji", "+679");
        countriesMap.put("Finland", "+358");
        countriesMap.put("France", "+33");
        countriesMap.put("French Antilles", "+596");
        countriesMap.put("French Guiana", "+594");
        countriesMap.put("French Polynesia", "+689");
        countriesMap.put("Gabon", "+241");
        countriesMap.put("Gambia", "+220");
        countriesMap.put("Georgia", "+995");
        countriesMap.put("Germany", "+49");
        countriesMap.put("Ghana", "+233");
        countriesMap.put("Gibraltar", "+350");
        countriesMap.put("Greece", "+30");
        countriesMap.put("Greenland", "+299");
        countriesMap.put("Grenada", "+1 473");
        countriesMap.put("Guadeloupe", "+590");
        countriesMap.put("Guam", "+1 671");
        countriesMap.put("Guatemala", "+502");
        countriesMap.put("Guinea", "+224");
        countriesMap.put("Guinea-Bissau", "+245");
        countriesMap.put("Guyana", "+595");
        countriesMap.put("Haiti", "+509");
        countriesMap.put("Honduras", "+504");
        countriesMap.put("Hong Kong SAR China", "+852");
        countriesMap.put("Hungary", "+36");
        countriesMap.put("Iceland", "+354");
        countriesMap.put("India", "+91");
        countriesMap.put("Indonesia", "+62");
        countriesMap.put("Iran", "+98");
        countriesMap.put("Iraq", "+964");
        countriesMap.put("Ireland", "+353");
        countriesMap.put("Israel", "+972");
        countriesMap.put("Italy", "+39");
        countriesMap.put("Ivory Coast", "+225");
        countriesMap.put("Jamaica", "+1 876");
        countriesMap.put("Japan", "+81");
        countriesMap.put("Jordan", "+962");
        countriesMap.put("Kazakhstan", "+7 7");
        countriesMap.put("Kenya", "+254");
        countriesMap.put("Kiribati", "+686");
        countriesMap.put("Kuwait", "+965");
        countriesMap.put("Kyrgyzstan", "+996");
        countriesMap.put("Laos", "+856");
        countriesMap.put("Latvia", "+371");
        countriesMap.put("Lebanon", "+961");
        countriesMap.put("Lesotho", "+266");
        countriesMap.put("Liberia", "+231");
        countriesMap.put("Libya", "+218");
        countriesMap.put("Liechtenstein", "+423");
        countriesMap.put("Lithuania", "+370");
        countriesMap.put("Luxembourg","+352");
        countriesMap.put("Macau SAR China", "+853");
        countriesMap.put("Macedonia", "+389");
        countriesMap.put("Madagascar", "+261");
        countriesMap.put("Malawi", "+265");
        countriesMap.put("Malaysia", "+60");
        countriesMap.put("Maldives", "+960");
        countriesMap.put("Mali", "+223");
        countriesMap.put("Malta", "+356");
        countriesMap.put("Marshall Islands", "+692");
        countriesMap.put("Martinique", "+596");
        countriesMap.put("Mauritania", "+222");
        countriesMap.put("Mauritius", "+230");
        countriesMap.put("Mayotte", "+262");
        countriesMap.put("Mexico", "+52");
        countriesMap.put("Micronesia", "+691");
        countriesMap.put("Midway Island", "+1 808");
        countriesMap.put("Moldova", "+373");
        countriesMap.put("Monaco", "+377");
        countriesMap.put("Mongolia", "+976");
        countriesMap.put("Montenegro", "+382");
        countriesMap.put("Montserrat", "+1664");
        countriesMap.put("Morocco", "+212");
        countriesMap.put("Myanmar", "+95");
        countriesMap.put("Namibia", "+264");
        countriesMap.put("Nauru", "+674");
        countriesMap.put("Nepal", "+977");
        countriesMap.put("Netherlands", "+31");
        countriesMap.put("Netherlands Antilles", "+599");
        countriesMap.put("Nevis", "+1 869");
        countriesMap.put("New Caledonia", "+687");
        countriesMap.put("New Zealand", "+64");
        countriesMap.put("Nicaragua", "+505");
        countriesMap.put("Niger", "+227");
        countriesMap.put("Nigeria", "+234");
        countriesMap.put("Niue", "+683");
        countriesMap.put("Norfolk Island", "+672");
        countriesMap.put("North Korea", "+850");
        countriesMap.put("Northern Mariana Islands", "+1 670");
        countriesMap.put("Norway", "+47");
        countriesMap.put("Oman", "+968");
        countriesMap.put("Pakistan", "+92");
        countriesMap.put("Palau", "+680");
        countriesMap.put("Palestinian Territory", "+970");
        countriesMap.put("Panama", "+507");
        countriesMap.put("Papua New Guinea", "+675");
        countriesMap.put("Paraguay", "+595");
        countriesMap.put("Peru", "+51");
        countriesMap.put("Philippines", "+63");
        countriesMap.put("Poland", "+48");
        countriesMap.put("Portugal", "+351");
        countriesMap.put("Puerto Rico", "+1 787");
        countriesMap.put("Qatar", "+974");
        countriesMap.put("Reunion", "+262");
        countriesMap.put("Romania", "+40");
        countriesMap.put("Russia", "+7");
        countriesMap.put("Rwanda", "+250");
        countriesMap.put("Samoa", "+685");
        countriesMap.put("San Marino", "+378");
        countriesMap.put("Saudi Arabia", "+966");
        countriesMap.put("Senegal", "+221");
        countriesMap.put("Serbia", "+381");
        countriesMap.put("Seychelles", "+248");
        countriesMap.put("Sierra Leone", "+232");
        countriesMap.put("Singapore", "+65");
        countriesMap.put("Slovakia", "+421");
        countriesMap.put("Slovenia", "+386");
        countriesMap.put("Solomon Islands", "+677");
        countriesMap.put("South Africa", "+27");
        countriesMap.put("South Georgia and the South Sandwich Islands", "+500");
        countriesMap.put("South Korea", "+82");
        countriesMap.put("Spain", "+34");
        countriesMap.put("Sri Lanka", "+94");
        countriesMap.put("Sudan", "+249");
        countriesMap.put("Suriname", "+597");
        countriesMap.put("Swaziland", "+268");
        countriesMap.put("Sweden", "+46");
        countriesMap.put("Switzerland", "+41");
        countriesMap.put("Syria", "+963");
        countriesMap.put("Taiwan", "+886");
        countriesMap.put("Tajikistan", "+992");
        countriesMap.put("Tanzania", "+255");
        countriesMap.put("Thailand", "+66");
        countriesMap.put("Timor Leste", "+670");
        countriesMap.put("Togo", "+228");
        countriesMap.put("Tokelau", "+690");
        countriesMap.put("Tonga", "+676");
        countriesMap.put("Trinidad and Tobago", "+1 868");
        countriesMap.put("Tunisia", "+216");
        countriesMap.put("Turkey", "+90");
        countriesMap.put("Turkmenistan", "+993");
        countriesMap.put("Turks and Caicos Islands", "+1 649");
        countriesMap.put("Tuvalu", "+688");
        countriesMap.put("U.S. Virgin Islands", "+1 340");
        countriesMap.put("Uganda", "+256");
        countriesMap.put("Ukraine", "+380");
        countriesMap.put("United Arab Emirates", "+971");
        countriesMap.put("United Kingdom", "+44");
        countriesMap.put("United States", "+1");
        countriesMap.put("Uruguay", "+598");
        countriesMap.put("Uzbekistan", "+998");
        countriesMap.put("Vanuatu", "+678");
        countriesMap.put("Venezuela", "+58");
        countriesMap.put("Vietnam", "+84");
        countriesMap.put("Wake Island", "+1 808");
        countriesMap.put("Wallis and Futuna", "+681");
        countriesMap.put("Yemen", "+967");
        countriesMap.put("Zambia", "+260");
        countriesMap.put("Zanzibar", "+255");
        countriesMap.put("Zimbabwe", "+263");
    }


    private static final CountryList instance = new CountryList();


    private CountryList() {
        // Private constructor to prevent instantiation
        this.setCountries();
    }

    public static CountryList getInstance() {
        return instance;
    }

    public Map<String, String> getCountriesMap() {
        return countriesMap;
    }


}
